### ISSUE TITLE
Docker image tag per kafka version?

### ISSUE THREAD

**Issue by kalbasit** [CloudTrackInc/kubernetes-kafka#1]
Thank you for your work! It works pretty well. Is it possible to tag the image with the Kafka version so we can rely on one version and upgrade manually?

**Comment by dreyk** [comment]
Yes. I have added Kafka version to Dockerfile. And you can now pull images for different version from hub.docker.com/r/cloudtrackinc/kubernetes-kafka

**Comment by kalbasit** [comment]
I see it now up on https://hub.docker.com/r/cloudtrackinc/kubernetes-kafka/tags/ Thank you!
